name: Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:

    #Checkout default
    - name: Checkout
      uses: actions/checkout@v4
    
    #action for python with version
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    #cache of Edge WebDriver
    - name: Cache Edge WebDriver
      uses: actions/cache@v4
      with:
        path: /home/runner/.cache/msedgedriver
        key: edgedriver-125.0.2535.85
  
    #Install dependencies of python 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #Install Microsoft Edge 
    - name: Install Microsoft Edge
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
        sudo apt update
        sudo apt install microsoft-edge-dev
    
    #Decrypt web driver for run after the test
    - name: Unzip local Edge WebDriver
      run: |
        unzip assets/edgedriver_linux64.zip
        sudo mv msedgedriver /usr/local/bin/
    
    #Check if installed web driver
    - name: Check Edge WebDriver
      run: msedgedriver --version

    #Run test of pytest with selenium
    #- name: Run Selenium Tests
    #  run: pytest 

    #Run test for generate report xml  
    - name: Run Selenium Tests with Report XML
      run: pytest --html=report.html

    #Lastly upload artifact
    - name: Updload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pytest-report
        path: report.html

    